[package]
name = "pipe_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
nix = "0.26.2"
tokio = {version = "1.28.2", features ="all"}
tun = "0.5.5"
